More verbose push script

diff --git a/docker_push b/docker_push
--- a/docker_push
+++ b/docker_push
@@ -1,5 +1,29 @@
 #!/usr/bin/env bash
 
-echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin >/dev/null 2>&1
-docker push $IMAGE_NAME >/dev/null 2>&1
-docker push $IMAGE_NAME:v$SONARR_VERSION >/dev/null 2>&1
+echo "Starting deployment to docker hub"
+echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
+if [ $? -ne 0 ]; then
+  echo "Login failed"
+  exit 1
+else
+  echo "Login OK"
+fi
+
+docker push "${IMAGE_NAME}":latest
+if [ $? -ne 0 ]; then
+  echo "Push latest failed"
+  exit 2
+else
+  echo "Push latest OK"
+fi
+
+docker push "${IMAGE_NAME}":v"${SONARR_VERSION}"
+if [ $? -ne 0 ]; then
+  echo "Push versioned failed"
+  exit 3
+else
+  echo "Push versioned OK"
+fi
+
+echo "Deployment done"
+exit 0
